version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ports:
      - "${ES_PORT}:9200"
    networks:
      - local-network
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.18.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    networks:
      - local-network
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  local-network:
    driver: bridge
